// this acts as the data source for the entire application

const data = {
  TableData: [
    {
      id: 1,
      name: "Auto Chess",
      region: "US",
      createdOn: 1623609000000,
      price: 30,
      csv: "Some CSV link for Whatsapp",
      report: "Some report link for Whatsapp",
      image_url: "game_1.png",
    },
    {
      id: 2,
      name: "Flow Free",
      region: "CA, FR",
      createdOn: 1607884200000,
      price: 45,
      csv: "Some CSV link for Super Jewels Quest",
      report: "Some report link for Super Jewels Ques",
      image_url: "game_2.png",
    },
    {
      id: 3,
      name: "Garena Free Fire",
      region: "FR",
      createdOn: 1646937000000,
      price: 50,
      csv: "Some CSV link for Mole Slayer",
      report: "Some report link for Mole Slayer",
      image_url: "game_3.png",
    },
    {
      id: 4,
      name: "MORTAL KOMBAT",
      region: "JP",
      createdOn: 1625077800000,
      price: 60,
      csv: "Some CSV link for Mancala Mix",
      report: "Some report link for Mancala Mix",
      image_url: "game_4.png",
    },
    {
      id: 5,
      name: "PUBG MOBILE",
      region: "US",
      createdOn: 1625596200000,
      price: 70,
      csv: "Some CSV link for Mancala Mix",
      report: "Some report link for Mancala Mix",
      image_url: "game_5.png",
    },
    {
      id: 6,
      name: "Need for Speed No Limits",
      region: "US",
      createdOn: 1630521000000,
      price: 20,
      csv: "Some CSV link for Mancala Mix",
      report: "Some report link for Mancala Mix",
      image_url: "game_6.png",
    },
    {
      id: 7,
      name: "Shadow Fight 3",
      region: "US",
      createdOn: 1616437800000,
      price: 19,
      csv: "Some CSV link for Mancala Mix",
      report: "Some report link for Mancala Mix",
      image_url: "game_7.png",
    },
    {
      id: 8,
      name: "Summoners War",
      region: "US",
      createdOn: 1640975400000,
      price: 65,
      csv: "Some CSV link for Mancala Mix",
      report: "Some report link for Mancala Mix",
      image_url: "game_8.png",
    },
  ],
};
export default data;
